name: "🐛 Bug Report"
description: "File a bug report to help us improve the node."
title: "[BUG] "
labels: ["bug", "new"]
assignees: "rookiepsi"

body:
  - type: checkboxes
    id: pre-submission-checklist
    attributes:
      label: "Pre-submission Checklist"
      description: "Please confirm you have done the following before submitting."
      options:
        - label: "I have searched the existing issues and am confident this is not a duplicate."
          required: true
        - label: "I have updated ComfyUI to the latest version."
          required: true
        - label: "I have updated this custom node to the latest version (`git pull` in the node's folder)."
          required: true
        - label: "I have tested this in a clean ComfyUI environment with no other custom nodes installed."
          required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Please provide your environment details."
      value: |
        - **ComfyUI Version:**
        - **ComfyUI Frontend Version:**
        - **Custom Node Version:**
        - **Operating System:**
        - **Python Version:**
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of the bug. What happened, and what did you expect to happen?"
      placeholder: "Describe the unexpected behavior and what you thought should occur."
    validations:
      required: true

  - type: textarea
    id: reproduction-and-attachments
    attributes:
      label: "Reproduction Steps, Workflow & Screenshot"
      description: |
        Please provide the exact steps to reproduce the bug and attach your workflow `.json` file and a screenshot of the error.
      placeholder: |
        1. Load the attached workflow...
        2. Change the following setting...
        3. Queue the prompt and observe the error.

        (Don't forget to attach your workflow `.json` file and a screenshot of the error message.)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "If applicable, paste the full error log from your console/terminal here."
      render: shell
      placeholder: "Paste the full error text from your terminal here."
    validations:
      required: false
